name: scrapping_pubmed

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  scrapping_pubmed:
    runs-on: macOS-latest
    env:
      ATLAS_URL: ${{ secrets.ATLAS_URL }}
      ATLAS_COLLECTION: ${{ secrets.ATLAS_COLLECTION }}
      ATLAS_DB: ${{ secrets.ATLAS_DB }}
    steps:
    - name: Start time
      run: echo "$(date) ** $(TZ=Asia/Jakarta date)"
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - name: Install R packages
      run: |
        install.packages("rvest", dependencies = TRUE)
        install.packages("httr", dependencies = TRUE)
        install.packages("mongolite", dependencies = TRUE)
      shell: Rscript {0}
    - name: Run scrapping script
      run: Rscript scrapping_pubmed.R
